### PR TITLE
Having Fun with ChatGPT

### PR DESCRIPTION
**Pull request by evildarkarchon**
Creating a draft PR from my ChatGPT session. This is not meant to be serious, but could provide reference material.

### CODE REVIEW

**Comment by evildarkarchon** [comment]
WOW, I wasn't expecting that, I was just messing around, mind blown.

**Comment by GuidanceOfGrace** [comment]
The code still needs manual fixing in some places. It didn't correctly capitalize some variables and START CLEANING button states are broken, for starters. Although it's merged for now, I'm keeping it as a separate copy on my PC until I figure out what else is broken and clean up some things.

**Comment by evildarkarchon** [comment]
Yeah, I created this as a draft because I expected it to not work out of the box.

**Comment by evildarkarchon** [comment]
I'm excited to see the next version, even if you remove some of the changes, nerd that I am, I learned some things from this experience.

**Comment by GuidanceOfGrace** [comment]
See if you can figure out why STOP CLEANING isn't getting enabled after cleaning is started.

**Comment by evildarkarchon** [comment]
Can't seem to find the cause at the moment, I will resume my hunt later today, it's almost 5:30am where I am.

**Comment by GuidanceOfGrace** [comment]
Alright, no rush.

**Comment by evildarkarchon** [comment]
I reverted check_config() back to its original code and the start-stop-stopping button works as expected again.

**Pull request merged**
